import type { Metadata } from 'next'
import { Inter ,Dosis } from 'next/font/google'
import './globals.css'
import DivLogo from './components/DivLogo/DivLogo'



const inter = Inter({ subsets: ['latin'] , variable:"--font-inter" })
const dosis = Dosis({ subsets: ['latin'] , variable:"--font-dosis" })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">

      <body className={`${dosis.variable} ${inter.variable} flex flex-col items-center mt-10 bg-neutral-900`}>
       <DivLogo />
        {children}
      </body>
    </html>
  )
}
